build:
    environment:
        php:
            version: 7.2
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        tests-and-coverage:
            tests:
                override:
                    - command: './vendor/bin/phpunit --coverage-clover=coverage.clover'
                      coverage:
                          file: 'coverage.clover'
                          format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
